name: CI

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  JAVA_OPTS: >-
    -Xms4096M -Xmx4096M -Xss6M
    -Dfile.encoding=UTF-8
    --add-opens java.base/java.lang=ALL-UNNAMED

jobs:
  test_scala:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      name: Cache Embedded Cassandra
      with:
        path: |
          ~/.embedded-cassandra
        key: cassandra-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**') }}
    - uses: coursier/cache-action@v6
      with:
        extraKey: '2.13'
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up scala
      uses: sbt/setup-sbt@159bc2bcdce6cc8f23f9faa80a0efc07632b17b9
    - run: sbt -v test quine/assembly quine-docs/generateDocs 'scalafixAll --check'

  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
      with:
        extraKey: 'fmt'
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up scala
      uses: sbt/setup-sbt@159bc2bcdce6cc8f23f9faa80a0efc07632b17b9
    - run: sbt -v scalafmtCheckAll scalafmtSbtCheck

